### ISSUE TITLE
Publish using "Produce single file" - Unhandled exception. System.ArgumentException: The path is empty. (Parameter 'path')

### ISSUE THREAD

**Issue by stesee** [hardkoded/puppeteer-sharp#2073]
### Description

PuppeteerSharp 9.0.0 introduced a bug that will cause to fail the parameterless ctor of BrowserFetcher when using in some published exe with "Produce single file" enabled.

### Complete minimal example reproducing the issue

- Get any example code that uses the parameterless ctor of BrowserFetcher and put it into a console application (.net6 and .net7 are known to cause the issue)
- Publish project with option "Produce single file" enabled.
- Run the published exe
- [Minimal repro](https://github.com/stesee/PuppeteerSharpMinimalRepro)

### Expected behavior:

Running without exception, like PuppeteerSharp 8.

### Actual behavior:

```
Unhandled exception. System.ArgumentException: The path is empty. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path)
   at System.IO.FileInfo..ctor(String originalPath, String fullPath, String fileName, Boolean isNormalized)
   at System.IO.FileInfo..ctor(String fileName)
   at PuppeteerSharp.BrowserFetcher.GetExecutablePath() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\BrowserFetcher.cs:line 354
   at PuppeteerSharp.BrowserFetcher..ctor() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\BrowserFetcher.cs:line 53
   at Program.<Main>$(String[] args) in C:\source\repos\PuppeteerSharpMinimalRepro\PuppeteerSharpMinimalRepro\Program.cs:line 5
   at Program.<Main>(String[] args)
```

### Versions

* Which version of PuppeteerSharp are you using? 9.0.0 and 9.0.1
* Which .NET runtime and version are you targeting? .net6 and .net7

### Additional Information - Workarround - Use overloads of the BrowserFetcher ctor.

```
var options = new BrowserFetcherOptions();
options.Path = Path.GetTempPath();
using var browserFetcher = new BrowserFetcher(options);
var revisionInfo = await browserFetcher.DownloadAsync();
await using var browser = await Puppeteer.LaunchAsync(new LaunchOptions { Headless = true, ExecutablePath = revisionInfo.ExecutablePath });
await using var page = await browser.NewPageAsync();
await page.GoToAsync("http://www.google.com");
await page.ScreenshotAsync("google.jpg");
```

**Comment by amaitland** [comment]
> In .NET 5 and later versions, for bundled assemblies, the value returned is an empty string.

As per https://learn.microsoft.com/en-us/dotnet/api/system.reflection.assembly.location?view=net-5.0

For `Publish Single File` the `Assembly.Location` will return an empty string. 

https://github.com/hardkoded/puppeteer-sharp/blob/087228c042de84e28e65a53d5459c42c343f058e/lib/PuppeteerSharp/BrowserFetcher.cs#L353

For `Single File exe` there won't be a copy of `PuppeteerSharp.dll` on disk. The check to see if file exists might need to be reconsidered.

**Comment by stesee** [comment]
@amaitland  You are right... maybe the behavior of PuppeteerSharp 8* can be brought back as fallback, when Assembly.Location is empty.

**Comment by kblok** [comment]
Yeah. We should fix this.

**Comment by kblok** [comment]
v9.0.2 is being cooked at the moment.

**Comment by stesee** [comment]
mh... would you accept a pr that automate publishing to nuget.org using github actions?

**Comment by kblok** [comment]
@stesee please!

**Comment by stesee** [comment]
It seems that "Improve DownloadFetcher executable path #2074" did not solve the issue. 

Testing this using https://github.com/stesee/PuppeteerSharpMinimalRepro/blob/master/PuppeteerSharpMinimalReproTests/PuppeteerSharpMinimalReproTests.cs

resulting in 

```
.\PuppeteerSharpMinimalRepro.exe
AppDomain.BaseDirectory: C:\PuppeteerSharpMinimalRepro\PuppeteerSharpMinimalRepro\bin\Release\net6.0\publish\
typeof(Puppeteer).Assembly.Location:
Unhandled exception. System.NotSupportedException: CodeBase is not supported on assemblies loaded from a single-file bundle.
   at System.Reflection.RuntimeAssembly.get_CodeBase()
   at PuppeteerSharp.BrowserFetcher.GetExecutablePath() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\BrowserFetcher.cs:line 356
   at PuppeteerSharp.BrowserFetcher..ctor() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\BrowserFetcher.cs:line 53
   at Program.<Main>$(String[] args) in C:\PuppeteerSharpMinimalRepro\PuppeteerSharpMinimalRepro\Program.cs:line 5
   at Program.<Main>(String[] args)
```

**Comment by kblok** [comment]
Ops. PRs are welcome :)

**Comment by amaitland** [comment]
See https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview?tabs=cli#api-incompatibility for list of known `APIs` that are incompatible with `SingleFile` builds.
